### ISSUE TITLE
Add example for multimodule project

### ISSUE THREAD

**Issue by jonenst** [simpligility/ossrh-demo#1]
Hi,
it would be great to add an example of a multimodule project using maven 3.6.1  because it's easy to get wrong urls

See https://issues.apache.org/jira/browse/MNG-6059

If I understand correctly, one should use
```
    project/@child.project.url.inherit.append.path = false
    project/scm/@child.scm.connection.inherit.append.path = false
    project/scm/@child.scm.developerConnection.inherit.append.path = false
    project/scm/@child.scm.url.inherit.append.path = true (by default so omitted)
```

Note: DistributionManagement/site is not shown in this example so I ignored it

**Comment by mosabua** [comment]
I dont actively maintain this project. It was just a simple demo in the past. You can look at my other projects like maven-repository-tools or takari/polyglot-maven and many others for examples.

**Comment by jonenst** [comment]
Ok thanks. For info your project is linked to by this page: https://central.sonatype.org/pages/requirements.html at the bottom

**Comment by mosabua** [comment]
I know .. I wrote 90% of the content on that site..

**Comment by jonenst** [comment]
Oh ok.
Then maybe you can update the page to link to projects that are maintained ? Or not, as you wish.
Thanks for your time.

**Comment by mosabua** [comment]
I no longer have access to that site and my example here is still valid and works just fine. I just dont plan on expanding it. What is the specific problem you are experiencing? Maybe ask on the Maven users mailing list for help to reach a wider base of helper. I am there as well.

**Comment by jonenst** [comment]
> What is the specific problem you are experiencing? 

if you have a multimodule project with :
```
pom.xml #  <- defined like your example
A/pom.xml  # <- no added information
```
then unless you use the new attributes that I mentioned at the beginning, the urls for the child artifact are wrong (project.url, scm.connection, scm.developerConnection) (they are parent_url/A which doesn't exist). You either have to repeat all the urls in child poms, or use the new attributes.

I was just trying to help people with multimodule projects to correctly configure their poms.

**Comment by mosabua** [comment]
I am not sure that is true. You can always make your own example to check and talk to Sonatype about adding a link to your project. This example has to stay simple as it is. And unfortunately I do not have the time to create another example ... too many other open source efforts ongoing already.
