### ISSUE TITLE
Incorrect developerConnection SCM URL in pom.xml

### ISSUE THREAD

**Issue by vg2902** [simpligility/ossrh-demo#2]
According to http://maven.apache.org/scm/git.html, git ssh URL takes the following form:

**scm:git:ssh://server_name[:port]/path_to_repository**

However, in the URL below the host and repository names are separated by a colon:

https://github.com/simpligility/ossrh-demo/blob/a1a78460ae500c3f605f4175bb358c8b15db5da8/pom.xml#L28

Shouldn't it be a slash instead?

```xml
<developerConnection>scm:git:ssh://github.com/simpligility/ossrh-demo.git</developerConnection> 
```

**Comment by mosabua** [comment]
Not sure.. maybe both work. The current setup definitely worked in the past when I used this and recorded the demo video for it.
