### ISSUE TITLE
scm.connection in pom.xml seems incorrect

### ISSUE THREAD

**Issue by tristan957** [simpligility/ossrh-demo#4]
You have `scm:git:git://...`, but it seems like it should be `scm:git:https://...` similar to `scm:git:ssh://...`

**Comment by mosabua** [comment]
No ... the one that is in the project now works. For reference.. others will work as well. 

https://maven.apache.org/scm/git.html

**Comment by tristan957** [comment]
I see. Thanks for pointing me at that link.
